runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: web/static/favicon.ico
  upload: web/static/favicon.ico

- url: /dist
  default_expiration: 1m
  static_dir: web/dist

- url: /static
  static_dir: web/static

- url: /.*
  script: _go_app
