runtime: go116

handlers:
- url: /favicon.ico
  static_files: web/static/favicon.ico
  upload: web/static/favicon.ico

- url: /dist
  expiration: 1m
  static_dir: web/dist

- url: /static
  static_dir: web/static

  # exists solely so that we can make the dir available to Go code
- url: /garbage/doc/api/v1
  static_dir: doccontent/api/dst

  # exists solely so that we can make the dir available to Go code
- url: /garbage/doc/guide
  static_dir: doccontent/guide/dst

- url: /doc/style.css
  static_files: doccontent/style.css
  upload: doccontent/style.css

- url: /.*
  script: auto
