// Code generated by "stringer -type=Color"; DO NOT EDIT.

package basiccolor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Red-0]
	_ = x[Orange-1]
	_ = x[Brown-2]
	_ = x[Yellow-3]
	_ = x[Green-4]
	_ = x[Blue-5]
	_ = x[Violet-6]
	_ = x[Pink-7]
	_ = x[Black-8]
	_ = x[Gray-9]
	_ = x[White-10]
}

const _Color_name = "RedOrangeBrownYellowGreenBlueVioletPinkBlackGrayWhite"

var _Color_index = [...]uint8{0, 3, 9, 14, 20, 25, 29, 35, 39, 44, 48, 53}

func (i Color) String() string {
	if i < 0 || i >= Color(len(_Color_index)-1) {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
